name: release

on: [push]

jobs:
  run-tests:
    uses: chris-mcdo/obscraper/.github/workflows/run-tests.yml@main
  
  publish:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')

    runs-on: ubuntu-latest

    needs: [run-tests]

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade build

    - name: Build package
      run: |
        python -m build

    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        repository_url: https://test.pypi.org/legacy/
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
