name: test
on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.9]
    steps:
    - name: Check out current commit
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    
    - name: Test with unittest
      run: tox -e ${{ matrix.python }}
