name: tests

on: [workflow_call]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        name: [
          "windows-py38",
          "ubuntu-py38",
          "macos-py38",
        ]

        include:
          - name: "windows-py38"
            os: windows-latest
            python: "3.8"
            tox_env: "py38"
            use_coverage: true

          - name: "ubuntu-py38"
            os: ubuntu-latest
            python: "3.8"
            tox_env: "py38"

          - name: "macos-py38"
            os: macos-latest
            python: "3.8"
            tox_env: "py38"

    steps:
    - name: Check out current commit
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Set up python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox coverage

    - name: Test without coverage
      if: "! matrix.use_coverage"
      run: "tox -e ${{ matrix.tox_env }}"

    - name: Test with coverage
      if: "matrix.use_coverage"
      run: "tox -e ${{ matrix.tox_env }}-coverage"

    - name: Generate coverage report
      if: "matrix.use_coverage"
      run: python -m coverage xml

    - name: Upload coverage to Codecov
      if: "matrix.use_coverage"
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        files: ./coverage.xml
        verbose: true
