name: tests

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out current commit
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox coverage

      - name: Test with coverage
        run: "tox -e py38-coverage"

      - name: Generate coverage report
        run: python -m coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./coverage.xml
          verbose: true
